"use client";

import { useState, useEffect } from "react";
import Image from "next/image";
import { motion, AnimatePresence } from "framer-motion";
import {
  Sprout, Users, Target, Lightbulb, Award,
  ArrowRight, Leaf, Globe, Heart, Zap
} from "lucide-react";
import Header from "@/components/shared/Header";

// ─── Tab data ─────────────────────────────────────────────────────────────────

// ─── Resolve CSS variable accent (client-side only) ──────────────────────────
function useAccent(tab) {
  const [accent, setAccent] = useState("#2E7D32");
  useEffect(() => {
    const val = getComputedStyle(document.documentElement)
      .getPropertyValue(tab.accentVar).trim();
    if (val) setAccent(val);
  }, [tab.accentVar]);
  return { accent, accentLight: `${accent}${tab.accentAlpha}` };
}

// ─── Tab data ─────────────────────────────────────────────────────────────────

const TABS = [
  {
    id: "story", label: "Our Story", icon: Sprout,
    accentVar: "--color-primary", accentAlpha: "18",
    badge: "Since 2022",
    headline: "Rooted in the Fields of Bangladesh",
    subline: "How a simple question — 'why do farmers still lose crops?' — became a mission.",
    paragraphs: [
      "SmartAgri was born in the summer of 2022, when a group of agronomists, software engineers, and rural economists gathered in a small office in Dhaka with one shared frustration: despite decades of agricultural research, Bangladeshi farmers were still losing 30–40% of their harvests to preventable causes — wrong planting times, ignored soil signals, unpredicted weather shifts.",
      "Our founders had seen this up close. One had grown up in Rajshahi watching his family's mango orchards wither from decisions made on guesswork rather than data. Another had spent years collecting DAE field reports that never reached the people who needed them most. The gap between agricultural knowledge and the farmer in the field was staggering — and entirely solvable.",
      "We spent the first year not building software, but listening. Over 400 farm visits across 18 districts. Conversations in Bangla, in dialect, in silence while walking between rice paddies at dusk. We learned that farmers didn't need more advice — they needed the right advice, at the right moment, in a language they trusted.",
      "SmartAgri launched its first planner tool in early 2023, and within six months, over 12,000 farmers had used it to generate DAE-certified crop plans. Today, we're Bangladesh's fastest-growing agri-tech platform — and we're only getting started.",
    ],
    stat: { value: "12,000+", label: "farmers in year one" },
  },
  {
    id: "mission", label: "Mission", icon: Target,
    accentVar: "--color-chart-2", accentAlpha: "22",
    badge: "Why We Exist",
    headline: "Every Farmer Deserves Expert Guidance",
    subline: "Our mission is to close the knowledge gap between agricultural science and the farming community.",
    paragraphs: [
      "Bangladesh feeds 170 million people from 8.5 million hectares of farmland — one of the highest crop densities on earth. Yet the average smallholder farmer makes critical decisions — what to plant, when, how much to irrigate, when to apply which fertilizer — based on tradition, instinct, and whatever the neighbour said last week.",
      "Our mission is singular: democratise access to precision agricultural knowledge. Not by replacing the farmer's intuition, but by augmenting it. A crop plan generated by SmartAgri synthesises Bangladesh DAE guidelines, 40 years of regional yield data, local soil profiles, and real-time weather intelligence — and delivers it in under 30 seconds.",
      "We measure our success not in app downloads or revenue, but in outcomes: reduced input waste, increased yield per bigha, fewer crop failures during flood and drought years. Every metric we track points back to one question — is the farmer better off this season than last?",
      "By 2027, we aim to reach every district in Bangladesh with tools that are offline-capable, voice-enabled in Bangla, and calibrated to hyper-local conditions. Agricultural intelligence should not be a luxury. It is a right.",
    ],
    stat: { value: "64", label: "districts in our target" },
  },
  {
    id: "team", label: "Our Team", icon: Users,
    accentVar: "--color-chart-3", accentAlpha: "22",
    badge: "The People",
    headline: "Builders, Farmers & Scientists — Together",
    subline: "A multidisciplinary team united by respect for the land and the people who work it.",
    paragraphs: [
      "Our 34-person team spans Dhaka, Rajshahi, Sylhet, and Khulna. We are agronomists with PhDs and farmers' sons who never finished school. We are full-stack engineers and women who rode motorbikes through flooded village roads to run field surveys. What unites us is not credential — it's conviction.",
      "Our agricultural science team works directly with the Bangladesh Department of Agricultural Extension, continuously updating our crop recommendation database as new DAE guidelines are released. Our data team maintains live integrations with Bangladesh Meteorological Department feeds and a growing network of IoT soil sensors deployed in partnership with local NGOs.",
      "We believe deeply in building with, not for, our users. Every new feature on SmartAgri goes through what we call 'the field test' — real farmers, in real conditions, with real stakes. If a 58-year-old rice farmer in Bogura can't use it without help, it doesn't ship.",
      "We are hiring. If you are passionate about food security, rural technology, or climate-resilient agriculture, we want to hear from you. We care far more about what you believe than where you studied.",
    ],
    stat: { value: "34", label: "team members across BD" },
  },
  {
    id: "technology", label: "Technology", icon: Lightbulb,
    accentVar: "--color-chart-4", accentAlpha: "22",
    badge: "How It Works",
    headline: "Intelligence Built on Decades of Data",
    subline: "Cutting-edge models grounded in Bangladesh's agricultural realities — not imported assumptions.",
    paragraphs: [
      "The SmartAgri recommendation engine draws on the largest structured dataset of Bangladesh agricultural outcomes ever assembled: crop yield records from 1983–2024, 1.2 million DAE field extension reports, soil survey data from the Soil Resource Development Institute, and real-time feeds from 47 meteorological stations across the country.",
      "Our planner uses a hybrid approach: rule-based expert systems encoding DAE guidelines ensure every recommendation is compliant with national standards, while machine learning layers personalise advice based on district, season, soil type, and historical local yield variance. The result is a plan that is both scientifically rigorous and contextually precise.",
      "We built our backend to be resilient to Bangladesh's infrastructure realities. Plans are generated server-side and cached aggressively for offline access. Our mobile app is optimised for 2G conditions and compresses data to under 50KB per plan request — because connectivity in Char islands and haor regions is not a given.",
      "We take data privacy seriously. Farmer data is anonymised, never sold, and stored on servers within Bangladesh in compliance with the Digital Security Act. Our open-source contributions to the Bangla NLP ecosystem are part of our commitment to the wider tech community.",
    ],
    stat: { value: "1.2M", label: "DAE field reports indexed" },
  },
  {
    id: "impact", label: "Impact", icon: Award,
    accentVar: "--color-chart-5", accentAlpha: "22",
    badge: "Proof in the Field",
    headline: "Real Change, Measured Season by Season",
    subline: "Numbers mean nothing without the stories behind them. Here are both.",
    paragraphs: [
      "In the 2023 Boro season, farmers using SmartAgri crop plans in Dinajpur and Rangpur reported an average 18% increase in rice yield per bigha compared to their previous season — without increasing fertilizer or irrigation input. The gains came almost entirely from better planting timing and variety selection aligned to local soil profiles.",
      "During the 2024 flash flood emergency in Sylhet, our early-warning integration allowed over 8,000 registered farmers to receive district-specific crop salvage advisories within 6 hours of BMD flood alerts — compared to the standard 3–5 day delay for traditional extension service communications. Post-flood surveys showed a 40% reduction in total crop loss among SmartAgri users versus non-users in the same upazilas.",
      "We partnered with BRAC in 2024 to bring SmartAgri to 50,000 women farmers across 12 districts, providing tailored plans in plain Bangla with voice readout capability. Early results show women farmers using the platform spend 22% less on inputs while achieving comparable or better yields — a direct contribution to household income and food security.",
      "SmartAgri was recognised by the Bangladesh ICT Division as a Top 10 Agri-Tech Innovation in 2024, and shortlisted for the FAO Digital Agriculture Award. But the recognition we value most is simpler: a farmer in Mymensingh telling our field team that last season was the first in twelve years he didn't have to borrow money after harvest.",
    ],
    stat: { value: "18%", label: "avg. yield increase, Boro '23" },
  },
];


// ─── Floating leaves ──────────────────────────────────────────────────────────

function FloatingLeaves() {
  const leaves = ["🌿", "🌾", "🍃", "🌱"];
  return (
    <>
      {leaves.map((leaf, i) => (
        <motion.div
          key={i}
          className="absolute text-2xl pointer-events-none select-none"
          style={{
            top: `${15 + i * 18}%`,
            left: i % 2 === 0 ? `${4 + i * 2}%` : undefined,
            right: i % 2 !== 0 ? `${4 + i * 2}%` : undefined,
          }}
          animate={{ y: [0, -16, 0], rotate: [0, 8, -8, 0], opacity: [0.08, 0.16, 0.08] }}
          transition={{ duration: 5 + i * 1.5, repeat: Infinity, delay: i * 0.7, ease: "easeInOut" }}
        >
          {leaf}
        </motion.div>
      ))}
    </>
  );
}

// ─── Page Banner ──────────────────────────────────────────────────────────────

function PageBanner() {
  return (
    <div className="relative h-56 sm:h-64 w-full">
      <Image
        src="/images/planner-bg.jpg"
        alt="About SmartAgri"
        fill
        className="object-cover object-center"
        sizes="100vw"
        quality={90}
        priority
      />
      <div className="absolute inset-0 bg-linear-to-b from-black/50 via-black/40 to-black/75" />
      <div className="absolute inset-0 bg-primary/25 mix-blend-multiply" />

      <FloatingLeaves />

      <div className="absolute inset-0 flex flex-col items-center justify-center text-center px-4 mt-6">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full
            bg-highlight/20 border border-highlight/40 text-highlight
            text-xs font-bold tracking-widest uppercase mb-4"
        >
          <Heart size={13} />
          About SmartAgri
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 28 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1, duration: 0.8, ease: [0.22, 1, 0.36, 1] }}
          className="text-3xl sm:text-4xl font-extrabold text-white leading-tight tracking-tight mb-3"
        >
          Grown From the Soil,{" "}
          <span className="text-highlight">Built for the Farmer.</span>
        </motion.h1>

        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.3, duration: 0.6 }}
          className="text-white/60 text-sm max-w-sm"
        >
          Our story, mission, team, technology and impact — all in one place
        </motion.p>
      </div>
    </div>
  );
}

// ─── Animated word reveal for headline ───────────────────────────────────────

function AnimatedHeadline({ text, accent }) {
  const words = text.split(" ");
  return (
    <h2 className="text-2xl sm:text-3xl font-extrabold text-foreground leading-tight mb-2">
      {words.map((word, i) => (
        <motion.span
          key={i}
          initial={{ opacity: 0, y: 18, filter: "blur(4px)" }}
          animate={{ opacity: 1, y: 0, filter: "blur(0px)" }}
          transition={{ delay: i * 0.06, duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
          className="inline-block mr-2"
        >
          {word}
        </motion.span>
      ))}
    </h2>
  );
}

// ─── Paragraph block with staggered reveal ───────────────────────────────────

function ParagraphBlock({ text, index }) {
  return (
    <motion.div
      initial={{ opacity: 0, x: -24 }}
      animate={{ opacity: 1, x: 0 }}
      transition={{ delay: 0.2 + index * 0.12, duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
      className="relative pl-5 border-l-2 mb-6 last:mb-0"
      style={{ borderColor: "var(--tab-accent, #16a34a)" }}
    >
      <motion.div
        initial={{ scaleY: 0 }}
        animate={{ scaleY: 1 }}
        transition={{ delay: 0.15 + index * 0.12, duration: 0.4 }}
        className="absolute left-[-2px] top-0 bottom-0 w-0.5 origin-top"
        style={{ backgroundColor: "var(--tab-accent, #16a34a)" }}
      />
      <p className="text-muted-foreground leading-relaxed text-sm sm:text-base">
        {text}
      </p>
    </motion.div>
  );
}

// ─── Stat pill ────────────────────────────────────────────────────────────────

function StatPill({ tab }) {
  const { accent, accentLight } = useAccent(tab);
  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.85 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ delay: 0.7, duration: 0.5, type: "spring", stiffness: 200 }}
      className="inline-flex items-center gap-3 px-5 py-3 rounded-2xl border mt-8"
      style={{ backgroundColor: accentLight, borderColor: `${accent}30` }}
    >
      <motion.span
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.85, duration: 0.4 }}
        className="text-2xl font-extrabold tracking-tight"
        style={{ color: accent }}
      >
        {tab.stat.value}
      </motion.span>
      <span className="text-sm text-muted-foreground font-medium">{tab.stat.label}</span>
    </motion.div>
  );
}

// ─── Tab button ───────────────────────────────────────────────────────────────

function TabButton({ tab, isActive, onClick, index }) {
  const Icon = tab.icon;
  const { accent, accentLight } = useAccent(tab);
  return (
    <motion.button
      initial={{ opacity: 0, y: -12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.07, duration: 0.4, ease: [0.22, 1, 0.36, 1] }}
      whileHover={{ y: -2 }}
      whileTap={{ scale: 0.96 }}
      onClick={onClick}
      className="relative flex items-center gap-2 px-4 py-3 rounded-xl text-sm font-semibold
        transition-colors whitespace-nowrap focus:outline-none"
      style={{
        color:           isActive ? accent : undefined,
        backgroundColor: isActive ? accentLight : "transparent",
      }}
    >
      <Icon size={15} />
      <span className="hidden sm:inline">{tab.label}</span>
      <span className="sm:hidden">{tab.label.split(" ")[0]}</span>
      <AnimatePresence>
        {isActive && (
          <motion.div
            layoutId="tab-underline"
            className="absolute bottom-0 left-3 right-3 h-0.5 rounded-full"
            style={{ backgroundColor: accent }}
            initial={{ scaleX: 0 }}
            animate={{ scaleX: 1 }}
            exit={{ scaleX: 0 }}
            transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
          />
        )}
      </AnimatePresence>
    </motion.button>
  );
}

// ─── Content section with decorative icon ────────────────────────────────────

function ContentSection({ tab }) {
  const Icon = tab.icon;
  const { accent, accentLight } = useAccent(tab);

  return (
    <motion.div
      key={tab.id}
      initial={{ opacity: 0, y: 30, scale: 0.98 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      exit={{ opacity: 0, y: -20, scale: 0.97 }}
      transition={{ duration: 0.45, ease: [0.22, 1, 0.36, 1] }}
      style={{ "--tab-accent": accent }}
    >
      {/* Section header */}
      <div className="flex items-start gap-4 mb-8">
        <motion.div
          initial={{ scale: 0, rotate: -20 }}
          animate={{ scale: 1, rotate: 0 }}
          transition={{ type: "spring", stiffness: 220, damping: 16, delay: 0.05 }}
          className="w-14 h-14 rounded-2xl flex items-center justify-center shrink-0 mt-1"
          style={{ backgroundColor: accentLight, border: `1.5px solid ${accent}30` }}
        >
          <Icon size={26} style={{ color: accent }} />
        </motion.div>

        <div className="flex-1 min-w-0">
          <motion.span
            initial={{ opacity: 0, x: -10 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.08, duration: 0.35 }}
            className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold
              tracking-widest uppercase mb-3"
            style={{ backgroundColor: accentLight, color: accent, border: `1px solid ${accent}25` }}
          >
            <Zap size={10} />
            {tab.badge}
          </motion.span>

          <AnimatedHeadline text={tab.headline} accent={accent} />

          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.3, duration: 0.5 }}
            className="text-muted-foreground text-sm leading-relaxed"
          >
            {tab.subline}
          </motion.p>
        </div>
      </div>

      {/* Divider */}
      <motion.div
        initial={{ scaleX: 0 }}
        animate={{ scaleX: 1 }}
        transition={{ delay: 0.25, duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
        className="h-px bg-border mb-8 origin-left"
      />

      {/* Paragraphs */}
      <div>
        {tab.paragraphs.map((para, i) => (
          <ParagraphBlock key={i} text={para} index={i} />
        ))}
      </div>

      {/* Stat pill */}
      <StatPill tab={tab} />
    </motion.div>
  );
}


// ─── Main page ────────────────────────────────────────────────────────────────

export default function AboutPage() {
  const [activeTab, setActiveTab] = useState("story");
  const currentTab = TABS.find((t) => t.id === activeTab);

  return (
    <div className="min-h-screen bg-background">
      <Header></Header>
      {/* Banner */}
      <PageBanner />

      {/* Content card — overlaps banner */}
      <div className="max-w-5xl mx-auto px-4 -mt-10 pb-16 relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 30, scale: 0.98 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
          className="bg-card border border-border rounded-3xl shadow-2xl shadow-black/10 overflow-hidden"
        >
          {/* ── Tab bar ── */}
          <div className="bg-muted/20 border-b border-border px-4 sm:px-6 py-3 overflow-x-auto">
            <div className="flex gap-1 min-w-max sm:min-w-0">
              {TABS.map((tab, i) => (
                <TabButton
                  key={tab.id}
                  tab={tab}
                  isActive={activeTab === tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  index={i}
                />
              ))}
            </div>
          </div>

          {/* ── Content ── */}
          <div className="p-6 sm:p-8 min-h-[520px]">
            <AnimatePresence mode="wait">
              <ContentSection key={activeTab} tab={currentTab} />
            </AnimatePresence>
          </div>
        </motion.div>

        {/* Footer note */}
        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.6 }}
          className="text-center text-xs text-muted-foreground mt-5
            flex items-center justify-center gap-1.5"
        >
          <Sprout size={12} className="text-primary" />
          SmartAgri — Empowering Bangladesh's farmers with precision agriculture.
        </motion.p>
      </div>
    </div>
  );
}